# Can be found at https://www.nerdfonts.com/font-downloads
font_family      MesloLGM Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 18.0

# Cursor
cursor_shape block
cursor_shape_unfocused hollow

# Spacing between text and outside borders
window_margin_width 10

# Colorscheme, attempts to mimic the transparency effect of Obsidian configuration
# Between 0-1 (0=opaque, 1=fully transparent.)
background_opacity 0.95
#Anything above 1 gives blur, values up to 64 work well.
background_blur 64
background_tint 3.0
mouse_hide_wait 3.0 
enable_audio_bell no
editor .

# BEGIN_KITTY_THEME
# VSCode_Dark (Can be set using the kitten command)
include current-theme.conf
# END_KITTY_THEME
